package info.appdev.charting.listener

import info.appdev.charting.data.BaseEntry
import info.appdev.charting.data.DataSet
import info.appdev.charting.data.Entry

/**
 * Listener for callbacks when drawing on the chart.
 */
interface OnDrawListener {
    /**
     * Called whenever an entry is added with the finger. Note this is also called for entries that are generated by the
     * library, when the touch gesture is too fast and skips points.
     *
     * @param entry the last drawn entry
     */
    fun onEntryAdded(entry: Entry)

    /**
     * Called whenever an entry is moved by the user after being highlighted
     */
    fun onEntryMoved(entry: Entry)

    /**
     * Called when drawing finger is lifted and the draw is finished.
     *
     * @param dataSet the last drawn DataSet
     */
    fun onDrawFinished(dataSet: DataSet<out BaseEntry<Float>, Float>)
}
