package info.appdev.charting.listener

import android.annotation.SuppressLint
import info.appdev.charting.data.DataSet
import info.appdev.charting.data.EntryFloat

/**
 * Listener for callbacks when drawing on the chart.
 */
interface OnDrawListener {
    /**
     * Called whenever an entry is added with the finger. Note this is also called for entries that are generated by the
     * library, when the touch gesture is too fast and skips points.
     *
     * @param entryFloat the last drawn entry
     */
    fun onEntryAdded(entryFloat: EntryFloat)

    /**
     * Called whenever an entry is moved by the user after being highlighted
     */
    fun onEntryMoved(entryFloat: EntryFloat)

    /**
     * Called when drawing finger is lifted and the draw is finished.
     *
     * @param dataSet the last drawn DataSet
     */
    fun onDrawFinished(@SuppressLint("RawTypeDataSet") dataSet: DataSet<*>)
}
