name: PullRequest

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  buildTest:
    name: Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macOS-13 ]
        java_version: [ 17 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
          submodules: true
      - name: prepare
        run: brew install exiftool imagemagick
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: ${{ matrix.java_version }}
      - uses: gradle/wrapper-validation-action@v3
      - name: Install Android SDK
        uses: hannesa2/action-android/install-sdk@0.1.16.7
      - name: Build project
        run: ./gradlew assembleDebug
      - name: Run tests
        run: ./gradlew test
      - name: Test jitpack publish command
        run: ./gradlew :MPChartLib:publishToMavenLocal
      - name: Run instrumentation tests
        uses: hannesa2/action-android/emulator-run-cmd@0.1.16.7
        with:
          cmd: ./gradlew cAT --continue
          api: 28
          tag: default
          abi: x86_64
          cmdOptions: -noaudio -no-boot-anim -no-window -metrics-collection
      - name: Archive Espresso results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: MPChart-Espresso-report
          path: MPChartExample/build/reports/androidTests/connected
          if-no-files-found: error
      - name: Archive screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: MPChart-Screenshots
          path: |
            MPChartExample/build/outputs/connected_android_test_additional_output/debugAndroidTest/connected
            MPChartExample/build/outputs/androidTest-results/connected
      - name: Compare screenshots
        run: |
          ls -ls MPChartExample/build/outputs/connected_android_test_additional_output/debugAndroidTest/connected
          cp MPChartExample/build/outputs/connected_android_test_additional_output/debugAndroidTest/connected/emulator\(AVD\)\ -\ 9/* screenshotsToCompare
          ./screenShotCompare.sh
      - name: Archive screenshots diffs
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: MPChart-Screenshots-diffs
          path: |
            screenshotDiffs
      - name: Show git status
        if: ${{ always() }}
        run: |
          git add screenshotsToCompare
          git status
          [ "$(git status -s -uno)" ] && exit 1 || exit 0
  Check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java_version: [ 17 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: hannesa2/action-android/install-sdk@0.1.16.7
      - name: Code checks
        run: ./gradlew check
      - name: Archive Lint report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: Chart-Lint-report
          path: ./**/build/reports/lint-results*.html
